import { Inter } from "next/font/google";
import NextAuthSessionProvider from "./nextauth/NextAuthSessionProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <NextAuthSessionProvider> {children}</NextAuthSessionProvider>
      </body>
    </html>
  );
}
